/home/haesungpyun/anaconda3/envs/llama/lib/python3.11/site-packages/fuzzywuzzy/fuzz.py:11: UserWarning: Using slow pure-python SequenceMatcher. Install python-Levenshtein to remove this warning
  warnings.warn('Using slow pure-python SequenceMatcher. Install python-Levenshtein to remove this warning')
Traceback (most recent call last):
  File "/home/haesungpyun/my_refpydst/src/refpydst/run_codex_experiment.py", line 366, in <module>
    args: CodexPromptingRunConfig = read_json(run_file)
                                    ^^^^^^^^^^^^^^^^^^^
  File "/home/haesungpyun/anaconda3/envs/llama/lib/python3.11/site-packages/refpydst/utils/general.py", line 38, in read_json
    return json.load(f)
           ^^^^^^^^^^^^
  File "/home/haesungpyun/anaconda3/envs/llama/lib/python3.11/json/__init__.py", line 293, in load
    return loads(fp.read(),
           ^^^^^^^^^^^^^^^^
  File "/home/haesungpyun/anaconda3/envs/llama/lib/python3.11/json/__init__.py", line 346, in loads
    return _default_decoder.decode(s)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/haesungpyun/anaconda3/envs/llama/lib/python3.11/json/decoder.py", line 337, in decode
    obj, end = self.raw_decode(s, idx=_w(s, 0).end())
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/haesungpyun/anaconda3/envs/llama/lib/python3.11/json/decoder.py", line 353, in raw_decode
    obj, end = self.scan_once(s, idx)
               ^^^^^^^^^^^^^^^^^^^^^^
json.decoder.JSONDecodeError: Invalid control character at: line 4 column 64 (char 138)
